### ISSUE TITLE
Clean up YAML-handling

### ISSUE THREAD

**Issue by busstoptaktik** [busstoptaktik/geodesy#23]
Likely, the pre-processing into PROJ-style tokens is superfluous (it was probably the result of early struggling with the crude YAML-Rust documentation, while still learning the basics of Rust)

**Comment by pka** [comment]
BTW, there's a new cool kid on the block called KML: https://github.com/kdl-org/kdl
Could be a good match for this kind of configuration.

**Comment by busstoptaktik** [comment]
This (and much more) done with the merge of the `unyaml` branch (3926f7b58ef9cd21bc93509325d3f2bbd935b11a and 41 more commits, unfortunately merged piecewise without a common merge commit)
