### ISSUE TITLE
Implementing Swiss Oblique Mercator

### ISSUE THREAD

**Issue by Rennzie** [busstoptaktik/geodesy#62]
For some reason I've not been able to tag you successfully in my PR over at geodesy-wasm. I've implemented the `somerc` operator and wondered if you'd rather I PR it into RG? 

https://github.com/Rennzie/geodesy-wasm/pull/27

**Comment by busstoptaktik** [comment]
That would be awesome! I am, however, mostly offline the next week-and-a-half, so review and merge will take some time (although I see that your implementation via proj-rs, is mostly identical to the original PROJ code, so probably not much to comment on there)

**Comment by Rennzie** [comment]
Great. I'll divert the PR into RG.

Yeah, I used the Proj swiss.pdf to re-write it. Hopefully it's a bit clearer than the Proj4.rs version which I couldn't get to work initially - likely because reading the variable soup made me cross eyed.
